### ISSUE TITLE
System.DllNotFoundException: 'Microsoft Visual C++ 2017-2019 Redistributable (x64)

### ISSUE THREAD

**Issue by nausixkiz** [AlturosDestinations/Alturos.Yolo#109]
System.DllNotFoundException: 'Microsoft Visual C++ 2017-2019 Redistributable (x64)'
Why it happened?
My system have all setup for Microsoft Visual C++ 2005-2019

**Comment by nguyenanhtuan1008** [comment]
I got exactly the same. Pls, help!!!

**Comment by sobelito** [comment]
I got this yesterday (had a working environment in vs2k17 and vs2k19), perhaps caused by upgrading to newest version of vs2k19, and was able to resolve by uninstalling all VS redistributables and then installing the one her matching my dev environment, I did 2k19:

https://stackoverflow.com/questions/12206314/detect-if-visual-c-redistributable-for-visual-studio-2012-is-installed/

**Comment by bernhardpetautschnig** [comment]
https://github.com/AlturosDestinations/Alturos.Yolo/issues/111
