### ISSUE TITLE
Bounding Box size issue

### ISSUE THREAD

**Issue by malibu** [AlturosDestinations/Alturos.Yolo#18]
Is there any additional conversion needed to convert the bounding box as returned by the API?
After calling "Detect", a list of YoloItem(s) are returned. The bounding boxes are accurate for larger objects but for smaller objects the returned boxes (X,Y, Width, Height) only overlap a small center portion of the true object in image co-ordinates.

`detections = yolo.Detect(bytes);`

YoloItem def:

    public int X { get; set; }

    public int Y { get; set; }

    public int Width { get; set; }

    public int Height { get; set; }

I see some python darknet examples where the size is scaled based on a factor inflating the boxes further?.
Is this needed?

**Comment by tinohager** [comment]
Can you explain the question better?

**Comment by malibu** [comment]
See the revised Question.

**Comment by tinohager** [comment]
I think this isn‘t needed. The returning bounding boxes is the real position on the input image. But on small objects in the image the detection not work very well. The reason is the image is scaled down before yolo processes it.

Depending on the configuration used yolov2 for example scaled down to 416x416 before detect some object.
