### ISSUE TITLE
Best Way to run multiple wrappers

### ISSUE THREAD

**Issue by Abutler101** [AlturosDestinations/Alturos.Yolo#68]
I'm not even sure that using multiple wrappers is what I need to do but I think it is - I need to run a system that takes several camera inputs (non overlapping FOV's) and detect objects in each of the camera frames. I can get it working with only a single wrapper but surely as the object detection on a given camera is un-related to any other camera (as far as yolo is concerned) there must be a way to use the built in parallel programming systems in c# to accelerate the process.

Currently when I attempt execution I get a memory access error the error occurs in the block of the yolo wrapper that copies the image array to unmanaged memory.

With GPU : Exception thrown at 0x00007FFD8EBB31E9 (yolo_cpp_dll_gpu.dll) in ImageStitching.exe: 0xC0000005: Access violation writing location 0x0000000000000000.

**Comment by tinohager** [comment]
I think the best option for you is use just one wrapper. Add the frames to a queue and process image one by one

**Comment by Abutler101** [comment]
Ah okay, fair enough. I guess I need to find an alternative, if everything has to go through the single wrapper that's going to be a mega bottleneck. I'm guessing it's a case of me not managing memory correctly.

**Comment by tinohager** [comment]
Do you use the graphics card?

**Comment by Abutler101** [comment]
Yeah, I'm running the pre-trained yolo-v3 model on a GTX 1050 feeding it  grey scale frames at 300x300 resolution (Yes I know it's a random resolution)

**Comment by MarcelMeurer** [comment]
I had the same challenge: Processing images with three different models. This doesn't work because If I try to use more then one wrapper I detect nothing.

I worked around: I build a single exe file which act as a WCF server. I start the exe file with three different configurations for the model (and for the port number for the service). With this separation, I reach my goal. Not beautiful but usable as a workaround.
