### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL yolo_cpp_dll_cpu.dll

### ISSUE THREAD

**Issue by rknidzam** [AlturosDestinations/Alturos.Yolo#9]
Hi, I have downloaded the package from Nuget Package Manager and try the basic detection code. But I am getting error "Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'x64\yolo_cpp_dll_cpu.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)". Any ideas what I'm missing here? Thanks.

**Comment by tinohager** [comment]
Exists the x64 folder on the output directory? Which Operating System you are use?

**Comment by rknidzam** [comment]
Yes. The folder is exist. I even double checked it with File.Exists() method to check and it returns true. 
I am using Windows 10 Pro Version 1803. Thanks for fast reply.

**Comment by tinohager** [comment]
Can you get me a list of all files available in your x64 folder?

**Comment by rknidzam** [comment]
My x64 folder contains all this:

- msvcr100.dll
- opencv_world340.dll
- pthreadGC2.dll
- pthreadVC2.dll
- yolo_cpp_dll_cpu.dll
- yolo_cpp_dll_gpu.dll

**Comment by tinohager** [comment]
Looks all fine.

Can you check with this tool are all dependencies exists? Open every dll in the x64 folder. Collapse the tree and check is anything red.

http://www.dependencywalker.com/

**Comment by rknidzam** [comment]
I tried to open one of dll from the x64 folder which is yolo_cpp_dll_cpu.dll with depedency walker. What I get is some red errors like:

**Error: At least one required implicit or forwarded dependency was not found.
Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.**

**Comment by tinohager** [comment]
Which cpu you are use? Can you test with an older nuget package?

https://www.nuget.org/packages/Alturos.Yolo/2.0.3

**Comment by tinohager** [comment]
It is not easy to debug your problem over github. Have you installed x64 c++ 2017 package?

**Comment by tinohager** [comment]
Uninstall all c++ 20XX packages on your machine. And try again install 2017.

**Comment by tinohager** [comment]
Any updates available?

**Comment by rknidzam** [comment]
Yes. It's still the same.

**Comment by tinohager** [comment]
Can you test the original project of AlexeyAB/darknet is this work on your machine?

**Comment by Osmosis311** [comment]
Hi,

I'm having the same issue.

![image](https://user-images.githubusercontent.com/360240/58989540-1e12fc80-87b2-11e9-8d5f-3147dc15add5.png)

**Comment by tinohager** [comment]
@Osmosis311 have you CUDA 10.0 installed?

**Comment by Nayra-Adel** [comment]
Hello,
I'm having the same issue.

My x64 folder contains all this:
msvcr100.dll
opencv_world340.dll
pthreadGC2.dll
pthreadVC2.dll
yolo_cpp_dll_cpu.dll
yolo_cpp_dll_gpu.dll

So it looks all fine, but after checking with this tool http://www.dependencywalker.com/
I got some red errors (opencv_world340 && yolo_cpp_dll_cpu)

![e1](https://user-images.githubusercontent.com/25779416/59559443-bc4f5f80-9007-11e9-8072-d9f487df2d06.png)

![e2](https://user-images.githubusercontent.com/25779416/59559444-bce7f600-9007-11e9-8941-d5b1eefb7dd2.png)

I'm using Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz & Visual Studio 2017
Any suggestions @tinohager ? Thanks

**Comment by nfvelado** [comment]
I had the same issue.  Downloaded the github source and opened the project in VS.  Commented out the following lines in YoloWrapper.cs, and the demo seems to work just fine:

this.EnvironmentReport = this.GetEnvironmentReport();
            /*if (!this.EnvironmentReport.MicrosoftVisualCPlusPlus2017RedistributableExists)
            {
                throw new DllNotFoundException("Microsoft Visual C++ 2017-2019 Redistributable (x64)");
            }*/

Haven't tried this library using the GPU yet, so not sure if this was a CPU related dependency or not.  Funny thing is this worked fine a week ago, then all of a sudden started throwing the exception a week later, but I can't recall anything that changed in the environment.

**Comment by xzessmedia** [comment]
For me it was enough to just use the redistributable link from the requirements of the readme and uninstall all previous
https://github.com/AlturosDestinations/Alturos.Yolo/blob/master/README.md

**Comment by metu** [comment]
For me the issue was that the DLL was genuinely not being imported because the code is looking for the x64 folder in the root directory of the running DLL (it needed to look one folder up).

My fix was to place the x64 folder in the bin folder. Was just a quick work around. You could maybe configure the folder to always be copied in the bin folder per build.

**Comment by SpiRaiL** [comment]
> For me it was enough to just use the redistributable link from the requirements of the readme and uninstall all previous
> https://github.com/AlturosDestinations/Alturos.Yolo/blob/master/README.md

I still don't have it working yet. But for this step I had to roll back the commits to the time when this comment was made. 
At that time the link was: https://go.microsoft.com/fwlink/?LinkId=746572
Currenlty is is: https://aka.ms/vs/16/release/vc_redist.x64.exe

While the file names are the same.... the content is not the same... 
And i had to uninstall the other distributions as xzessmedia suggests. 

Installing RedistributableChecker with NuGet is a handy way to workout exactly what you are using. 

However, i think this turns out to be a dead in because I dont think this previous version of the redistributor is then able to find the yolo_cpp_dll_cpu.dll files despite them being in the correct place. Using programs like "dependenies" highlights this. No amounts of moving these files around (like metu suggests) has helped me in this case.

**Comment by umutdag1** [comment]
> For me the issue was that the DLL was genuinely not being imported because the code is looking for the x64 folder in the root directory of the running DLL (it needed to look one folder up).
> 
> My fix was to place the x64 folder in the bin folder. Was just a quick work around. You could maybe configure the folder to always be copied in the bin folder per build.

What bin folder did you use to place x64 folder in ?

**Comment by umutdag1** [comment]
Guys, I have the same problem. But I am doing it with unity using C#. I did all the steps that you wrote above comments but it didn't work . Who has another idea to solve this issue ?

**Comment by dgiunchi** [comment]
I have the same issue as umutdag1 experienced. I tried to upgrade Yolo to 3.0.6 as to someone fixed but I still have the error.

**Comment by asverlov** [comment]
Maybe  a mix-up of release and debug code?  I had an exact same error when was trying to use release dll in debug build.

**Comment by raulsf6** [comment]
@umutdag1 any news? I have the same error with Unity

**Comment by jaopinheiro** [comment]
People, the problem is with ws2_32.dll in ...\windows\system32.dll

I discovered this because I installed the lucasg tool (Dependecies). You can download from: https://github/lucasg/Dependencies

On windows 10 the api-ms-win-core-wow64-l1-1-0.dll no longer exist. You can download it from https://pt.dll-files.com/

All you have to do is put this dll on ...\windows\system32 folder.

I hope I had help.
